manifest:
  remotes:
    - name: ze-or
      url-base: https://github.com/ze-or
  projects:
    - name: zmk
      remote: ze-or
      revision: ze-or/zen-v2+mouse+plover
      import: app/west.yml
  self:
    path: config